# Generated by Django 6.0.3 on 2026-03-10 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('openai_compatible', 'OpenAI-Compatible')], default='openai', max_length=30)),
                ('api_key', models.CharField(max_length=500)),
                ('base_url', models.CharField(blank=True, help_text='For OpenAI-compatible endpoints', max_length=255)),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
