# Generated by Django 6.0.3 on 2026-03-17 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providercollection',
            name='local_path',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProviderEmbeddingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hf_token', models.CharField(help_text='HuggingFace API token (hf_...)', max_length=500)),
                ('embed_model', models.CharField(default='Qwen/Qwen3-Embedding-8B', help_text='HuggingFace model ID used for embeddings', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
