# Generated by Django 6.0.3 on 2026-03-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
